# Generated by Django 3.1 on 2021-06-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search1',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
                ('State', models.CharField(max_length=120)),
                ('City', models.CharField(max_length=120)),
                ('Contact', models.IntegerField()),
            ],
            options={
                'db_table': 'b1121',
            },
        ),
    ]
