# Generated by Django 3.1 on 2021-06-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='search1',
            table=None,
        ),
    ]
