# Generated by Django 3.1 on 2021-06-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0002_auto_20210609_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='search1',
            name='Contact1',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
