# Generated by Django 3.2.4 on 2021-06-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0004_remove_search1_contact1'),
    ]

    operations = [
        migrations.CreateModel(
            name='subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
